### PR TITLE
Fixed installation failure due to missing dependency

### PR DESCRIPTION
**Pull request by marc-**
Fixed installation failure due to missing dependency.
See mkorpela/RoboMachine/issues/19 .

### CODE REVIEW

**Comment by mkorpela** [comment]
It will not fix the problem. Why would you want to do this?

**Comment by marc-** [comment]
The problem is that pip first tries to evaluate all `setup.py` files before installing anything. And it fails on `import robomachine` module, wich has `from pyparsing import *` in it. So, even you have `pyparsing` defined in you dependency section (`install_requires = ['pyparsing', 'argparse', 'robotframework']`), it will never get work until you install `pyparsing` first manually.

**Comment by mkorpela** [comment]
Yep. Your right. Thanks for pointing that out.

**Comment by mkorpela** [comment]
I now know that this was the exactly right fix. Can you redo a pull request as github doesn't allow me to take it again?

**Comment by marc-** [comment]
Sure, will do.

**Pull request closed without merging**
