### PR TITLE
Add support for two new variable conditions

### PR DESCRIPTION
**Pull request by bjornfor**
``` ${VAR} in (1,3)``` and ```${VAR} ~ REGEXP```

### CODE REVIEW

**Comment by bjornfor** [comment]
I pushed another commit to this PR: ```Add support for "${VAR} !~ REGEX" (negated regexp match)```

**Comment by mkorpela** [comment]
On those examples no escapes are made. But for example expecting a digit with \d requires \\d .. anyway it is a small thing.

Also the match mechanism will currently match if the beginning of the string will match. Is this expected?

**Comment by bjornfor** [comment]
Right. I guess ```\d``` might require escaping with ```\```. But I'm not sure, I didn't test it.

But even if that's the case, it is a cost that has to be paid only by those who want that extra functionality. For things that can be done with globbing, regexp doesn't seem to require any (more) escapes, as far as I can see.

There is also the option of having both glob and regex operators, like in bash. But I don't think that's worth it. (If we were to use bash operators, that would be backward incompatible change with respect to the current == operator.)

About matching the beginning of string, you mean the "search() vs match()" thing? Ref. https://docs.python.org/2/library/re.html#search-vs-match. I chose match() on purpose, because I think it is more precise (and thus flexible). But I have no idea if other people find the "search()" behaviour more appropriate.

**Comment by bjornfor** [comment]
I regret some of the stuff I wrote above. I now read the whole https://docs.python.org/2/library/re.html#search-vs-match and I agree that "search()" is better. (Explicit use of ```^``` to match the beginning of a string.)

**Comment by bjornfor** [comment]
There, I changed it from match() to search().

**Comment by bjornfor** [comment]
@mkorpela: Does it look OK now?

**Comment by mkorpela** [comment]
@bjornfor Yep. Sorry for not responding sooner.
Thanks for all the great work!

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
