### PR TITLE
Two fixes and one new feature

### PR DESCRIPTION
**Pull request by bjornfor**
See commits.

### CODE REVIEW

**Comment by bjornfor** [comment]
Please have a look at the commits before hitting "Merge", I may have made a mistake :-)

**Comment by bjornfor** [comment]
I find it strange that the ParseResults 'rules' attribute only have the first element, where e.g. 'variables' have all elements. They seem to be defined similarly, but still behave differently. There must be something I'm missing.

I also tried with setResultsName(..., listAllMatches=True), but that didn't work right.

The "parsing: take all rules into account, not just the first" commit in this PR is a bit of a hack, but it seems to work.

**Comment by bjornfor** [comment]
The less/greater than operators operate on strings. This may cause some unexpected results:

```
$ python -c "print('-1' > '-30')"
False
$ python -c "print('1.0' >= '1.00')"
False
```

But it works on positive integers though...

Do you think it'd be worth it to try converting the values to float/int before comparing? And if conversion fails, just leave the string as is, or raise an error?

**Comment by mkorpela** [comment]
I think the comparison should expect that the comparables are numbers for now.

**Comment by mkorpela** [comment]
I'll merge this anyway. I'll maybe try some changes to the comparator classes (might be that I can make them a little bit cleaner looking as there is quite a bit of repetition there).
Good stuff @bjornfor !

**Comment by bjornfor** [comment]
There are two more comparison changes I'd like to get in:

```${VAR} in (1, 5, 7)``` (shorthand for ```${VAR} == 1  or  ${VAR} == 5 ...``` and ```${VAR} ~ .*foo``` (regex match).

Just a heads up, if you're going to make cleanups. I'll post the PR shortly.

**Pull request merged**
